# Test parameter sweep - minimal example
simulation:
  nb_steps: 400000  # Shorter for testing
  obj_rate: 3.44
  with_decay: true
  with_plasticity: true  
  TR: 2.4
flp: 0.01
fhp: 0.1
  burnout: 8
  lrj: 1.13
  G: 2.9    
  parallel: true
  seed: 1

data:  
  test_mode: false  
  max_subjects_test: 1
  sc_root: "AAL"  
output:
  save_full_outputs: true  
  observables:
    - name: raw
      signal: rates
    - name: raw
      signal: bold
    - name: fc 
      signal: bold
    - name: raw
      signal: fic
    
      
  
experiment:
  description: "Showing firing rate stability across G values in the dynamic model"
  version: "1.1"
